
package rich.screens.clickgui.impl.autobuy.items.price;

import java.util.HashMap;
import java.util.Map;

public class Defaultpricec {
    private static final Map<String, Integer> defaultPrices = new HashMap<String, Integer>();

    public static int getPrice(String displayName) {
        return defaultPrices.getOrDefault(displayName, 1000);
    }

    static {
        defaultPrices.put("Diamond", 1000);
        defaultPrices.put("Diamond Ore", 1000);
        defaultPrices.put("Diamond Block", 1000);
        defaultPrices.put("Name Tag", 1000);
        defaultPrices.put("Block Damager", 1000);
        defaultPrices.put("Gold Block", 1000);
        defaultPrices.put("Divine Aura", 1000);
        defaultPrices.put("Divine Touch", 1000);
        defaultPrices.put("Crusher Boots", 1000);
        defaultPrices.put("Mace", 1000);
        defaultPrices.put("Crusher Mace", 1000);
        defaultPrices.put("Flash", 1000);
        defaultPrices.put("Wither Skeleton Head", 1000);
        defaultPrices.put("Dragon Head", 1000);
        defaultPrices.put("Zombie Head", 1000);
        defaultPrices.put("Creeper Head", 1000);
        defaultPrices.put("Piglin Head", 1000);
        defaultPrices.put("Skeleton Head", 1000);
        defaultPrices.put("Disorientation", 1000);
        defaultPrices.put("Dynamite", 1000);
        defaultPrices.put("Dragon Skin", 1000);
        defaultPrices.put("Iron Block", 1000);
        defaultPrices.put("Iron Ingot", 1000);
        defaultPrices.put("Mysterious Beacon", 1000);
        defaultPrices.put("Enchanted Golden Apple", 1000);
        defaultPrices.put("Nether Star", 1000);
        defaultPrices.put("Agent Potion", 1000);
        defaultPrices.put("Killer Potion", 1000);
        defaultPrices.put("Medic Potion", 1000);
        defaultPrices.put("Belch Potion", 1000);
        defaultPrices.put("Winner Potion", 1000);
        defaultPrices.put("Golden Apple", 1000);
        defaultPrices.put("Gold Ingot", 1000);
        defaultPrices.put("Emerald Ore", 1000);
        defaultPrices.put("Crusher Pickaxe", 1000);
        defaultPrices.put("Mega Bulldozer Pickaxe", 1000);
        defaultPrices.put("Trial Key", 1000);
        defaultPrices.put("Beacon", 1000);
        defaultPrices.put("Crusher Sword", 1000);
        defaultPrices.put("Bag", 1000);
        defaultPrices.put("Flash Urine", 1000);
        defaultPrices.put("Crusher Chestplate", 1000);
        defaultPrices.put("Netherite Block", 1000);
        defaultPrices.put("Netherite Ingot", 1000);
        defaultPrices.put("Netherite Upgrade", 1000);
        defaultPrices.put("Obsidian", 1000);
        defaultPrices.put("Fire tornado", 1000);
        defaultPrices.put("Sphere Key", 1000);
        defaultPrices.put("Blaze Rod", 1000);
        defaultPrices.put("Plast", 1000);
        defaultPrices.put("Crusher Leggings", 1000);
        defaultPrices.put("Gunpowder", 1000);
        defaultPrices.put("Cursed Soul", 1000);
        defaultPrices.put("Exp Bottle", 1000);
        defaultPrices.put("Exp Bottle [Lv.15]", 1000);
        defaultPrices.put("Exp Bottle [Lv.30]", 1000);
        defaultPrices.put("Exp Bottle [Lv.50]", 1000);
        defaultPrices.put("Silver", 1000);
        defaultPrices.put("Sulfuric Acid", 1000);
        defaultPrices.put("Signal Fire [Rich]", 1000);
        defaultPrices.put("Signal Fire [Legendary]", 1000);
        defaultPrices.put("Signal Fire [Normal]", 1000);
        defaultPrices.put("Signal Fire [Random]", 1000);
        defaultPrices.put("Frost Snowball", 1000);
        defaultPrices.put("Andromeda Sphere", 1000);
        defaultPrices.put("Apollo Sphere", 1000);
        defaultPrices.put("Astrea Sphere", 1000);
        defaultPrices.put("Osiris Sphere", 1000);
        defaultPrices.put("Pandora Sphere", 1000);
        defaultPrices.put("Titan Sphere", 1000);
        defaultPrices.put("Chimera Sphere", 1000);
        defaultPrices.put("Spawner", 1000);
        defaultPrices.put("Harmony Talisman", 1000);
        defaultPrices.put("Edge Talisman", 1000);
        defaultPrices.put("Daedalus Talisman", 1000);
        defaultPrices.put("Echidna Talisman", 1000);
        defaultPrices.put("Punisher Talisman", 1000);
        defaultPrices.put("Crusher Talisman", 1000);
        defaultPrices.put("Triton Talisman", 1000);
        defaultPrices.put("Phoenix Talisman", 1000);
        defaultPrices.put("TNT - TIER BLACK", 1000);
        defaultPrices.put("TNT - TIER WHITE", 1000);
        defaultPrices.put("Totem of Undying", 1000);
        defaultPrices.put("Trap", 1000);
        defaultPrices.put("Trident", 1000);
        defaultPrices.put("Crusher Trident", 1000);
        defaultPrices.put("Firework", 1000);
        defaultPrices.put("Shulker Box", 1000);
        defaultPrices.put("Crusher Helmet", 1000);
        defaultPrices.put("Elytra", 1000);
        defaultPrices.put("Ender Pearl", 1000);
        defaultPrices.put("Apple", 1000);
        defaultPrices.put("Visible Dust", 1000);
        defaultPrices.put("Vortex Egg", 1000);
        defaultPrices.put("Zombie Villager Egg", 1000);
        defaultPrices.put("Villager Egg", 1000);
        defaultPrices.put("Ominous Trial Key", 1000);
        defaultPrices.put("Chunk Loader [1x1]", 1000);
        defaultPrices.put("Chunk Loader [3x3]", 1000);
        defaultPrices.put("Chunk Loader [5x5]", 1000);
        defaultPrices.put("Crusher Crossbow", 1000);
        defaultPrices.put("Cake", 1000);
        defaultPrices.put("Devil Arrow", 1000);
        defaultPrices.put("Tipped Arrow", 1000);
        defaultPrices.put("Paranoia Arrow", 1000);
        defaultPrices.put("Ice Arrow", 1000);
        defaultPrices.put("Poison Arrow", 1000);
        defaultPrices.put("Cursed Arrow", 1000);
        defaultPrices.put("Wind Charge", 1000);
        defaultPrices.put("Vortex Rod", 1000);
        defaultPrices.put("Discord Talisman", 1000);
        defaultPrices.put("Tyrant Talisman", 1000);
        defaultPrices.put("Rage Talisman", 1000);
        defaultPrices.put("Vortex Talisman", 1000);
        defaultPrices.put("Darkness Talisman", 1000);
        defaultPrices.put("Demon Talisman", 1000);
        defaultPrices.put("Grinch Talisman", 1000);
        defaultPrices.put("Crusher Bow", 1000);
        defaultPrices.put("Firecracker", 1000);
        defaultPrices.put("Holy Water", 1000);
        defaultPrices.put("Wrath Potion", 1000);
        defaultPrices.put("Paladin Potion", 1000);
        defaultPrices.put("Assassin Potion", 1000);
        defaultPrices.put("Radiation Potion", 1000);
        defaultPrices.put("Sleeping Potion", 1000);
        defaultPrices.put("Tangerine Juice", 1000);
    }
}

